### PR TITLE
feature: Added capability to use custom telemetry logger for periodic telemetry sending

### PR DESCRIPTION
**Pull request by ponekbladh**
Update to the Commerce Essentials - Telemetry (CET) model in Commerce/Essentials/Telemetry to allow a custom telemetry logger to be injected easy.

### CODE REVIEW

**Comment by ponekbladh** [comment]
@microsoft-github-policy-service agree [company="DXC Technology"]

**Comment by ponekbladh** [comment]
@microsoft-github-policy-service agree company="DXC Technology"

**Comment by ponekbladh** [comment]
@AliAAdamu , Love your work! this is a great solution. I had the same idea just wasn't sure how to get the SQL stats. I hope this helps.

**Comment by RobBertram** [comment]
While this change allows the extensions in this project to use a different telemetry logger, it does nothing with the core monitoring framework.  I do not see how this would be generally used.

**Pull request closed without merging**
